DROP TABLE CUSTOMER;
DROP TABLE CUS_LEVEL;

CREATE TABLE CUS_LEVEL(
    LEVELNO   NUMBER(1) PRIMARY KEY,
    LEVELNAME VARCHAR2(20) NOT NULL);

CREATE SEQUENCE CUS_SQ MAXVALUE 9999;

CREATE TABLE CUSTOMER(
    CNO      NUMBER(4)    PRIMARY KEY,
    CNAME    VARCHAR2(50) NOT NULL,
    JOINDATE DATE         DEFAULT SYSDATE,
    PHONE    VARCHAR2(50) UNIQUE,
    POINT    NUMBER,
    LEVELNO  NUMBER(1)    REFERENCES CUS_LEVEL(LEVELNO));

INSERT INTO CUS_LEVEL VALUES (1, 'VVIP');
INSERT INTO CUS_LEVEL VALUES (2, 'VIP');
INSERT INTO CUS_LEVEL VALUES (3, 'NORMAL');
INSERT INTO CUS_LEVEL VALUES (4, 'BLACK');
INSERT INTO CUSTOMER VALUES (CUS_SQ.NEXTVAL, 'È«±æµ¿', 
        TO_DATE('20171017','YYYYMMDD'),'010-9999-9999',300,1);
INSERT INTO CUSTOMER VALUES (CUS_SQ.NEXTVAL, 'ÀÌÃ¶¼ö', 
        TO_DATE('20171112','YYYYMMDD'),'010-8888-8888',NULL,2);

SELECT * FROM CUSTOMER;
SELEXT * FROM CUS_LEVEL;