--실습예제(1)
DROP TABLE  MAJOR;
DROP TABLE  STUDENT;
CREATE TABLE MAJOR (
MAJOR_CODE NUMBER(2) PRIMARY KEY NOT NULL,
MAJOR_NAME VARCHAR2(100) NOT NULL,
MAJOR_OFFICE_LOC VARCHAR(100) NOT NULL
);

CREATE TABLE STUDENT(
STUDENT_CODE VARCHAR2(10) PRIMARY KEY NOT NULL,
STUDENT_NAME VARCHAR2(30),
SCORE NUMBER(3),
MAJOR_CODE NUMBER(2) REFERENCES MAJOR(major_CODE)
);

INSERT INTO MAJOR VALUES (1,'경영정보','3층 인문실');
INSERT INTO MAJOR VALUES (2,'소프트웨어공학','3층 인문실');
INSERT INTO MAJOR VALUES (3,'디자인','4층 과학실');
INSERT INTO MAJOR VALUES (4,'경제','4층 과학실');

INSERT INTO STUDENT VALUES ('A01','김길동',100,1);
INSERT INTO STUDENT VALUES ('A02','문길동',90,2);
INSERT INTO STUDENT VALUES ('A03','홍길동',95,1);

SELECT * FROM MAJOR;
SELECT * FROM STUDENT;

--실습예제(2)
DROP TABLE BOOKCATEGORY;
DROP TABLE BOOK;
CREATE TABLE BOOKCATEGORY(
CATEGORY_CODE NUMBER(5) PRIMARY KEY NOT NULL,
CATEGORY_NAME VARCHAR2(100) NOT NULL,
OFFICE_LOC VARCHAR2(200) NOT NULL
);

INSERT INTO BOOKCATEGORY VALUES (100,'철학', '3층 인문실');
INSERT INTO BOOKCATEGORY VALUES (200,'인문', '3층 인문실');
INSERT INTO BOOKCATEGORY VALUES (300,'자연과학', '4층 과학실');
INSERT INTO BOOKCATEGORY VALUES (400,'IT', '4층 과학실');

CREATE TABLE BOOK(
BOOKNO VARCHAR2(100) PRIMARY KEY NOT NULL,
BOOKNAME VARCHAR2(500) NOT NULL,
PUBLISHER VARCHAR2(200) NOT NULL,
PUBYEAR NUMBER(10) DEFAULT TO_CHAR(SYSDATE, 'YYYY') ,
CATEGORY_CODE NUMBER(5) REFERENCES BOOKCATEGORY(CATEGORY_CODE)
);

INSERT INTO BOOK VALUES ('100A01','철학자의 삶','더존출판',2017,100);
INSERT INTO BOOK VALUES ('400A01','철학자의 삶','더존출판',2017,400);

SELECT * FROM BOOK;
SELECT * FROM BOOKCATEGORY;