--DROP
DROP TABLE CUSTOMER CASCADE CONSTRAINTS;
DROP TABLE CUS_LEVEL;
DROP SEQUENCE CUTOMER_SEQ;

--테이블생성
CREATE TABLE CUS_LEVEL(
LEVELNO NUMBER(1,0) PRIMARY KEY,
LEVELNAME VARCHAR2(20),
LOW NUMBER(9,0),
HIGH NUMBER(9,0)
);

CREATE TABLE CUSTOMER(
CID NUMBER(6,0) PRIMARY KEY,
CTEL VARCHAR2(20) NOT NULL, 
CNAME VARCHAR2(30) NOT NULL,
CPOINT NUMBER(9) DEFAULT 1000,
CAMOUNT NUMBER(9) DEFAULT 0,
LEVELNO NUMBER(1,0) DEFAULT 1 REFERENCES CUS_LEVEL(LEVELNO));

DROP SEQUENCE CUSTOMER_SEQ;
CREATE SEQUENCE CUSTOMER_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999
MINVALUE 1
NOCYCLE
NOCACHE;

--데이터 INSERT
INSERT INTO CUS_LEVEL VALUES(1, 'NORMAL' ,0,99999);
INSERT INTO CUS_LEVEL VALUES(2, 'SIVER' ,1000000,1999999);
INSERT INTO CUS_LEVEL VALUES(3, 'GOLD' ,2000000,2999999);
INSERT INTO CUS_LEVEL VALUES(4, 'VIP' ,3000000,4999999);
INSERT INTO CUS_LEVEL VALUES(5, 'VVIP' ,5000000,999999999);
SELECT * FROM CUS_LEVEL;
INSERT INTO CUSTOMER (CID,CTEL,CNAME) VALUES (CUSTOMER_SEQ.NEXTVAL, '010-9999-9999','홍길동');
INSERT INTO CUSTOMER VALUES (CUSTOMER_SEQ.NEXTVAL, '010-8888-9999','김길동',1000,5000000,5);

SELECT  * FROM CUSTOMER;
SELECT * FROM CUS_LEVEL;
 -- 0. 레벨이름들 검색 : public Vector<String> getLevelNames()
 SELECT LEVELNAME FROM CUS_LEVEL ORDER BY LEVELNO;

-- 1. cId로 검색 : public CustomerDto cIdGetCustomer(int cId)
SELECT  CID, CTEL, CNAME, CPOINT,CAMOUNT, LEVELNAME,HIGH - CAMOUNT+1  FORLEVELUP
FROM CUSTOMER C , CUS_LEVEL L
WHERE C.LEVELNO = L.LEVELNO
AND CID = 1; -- 최고 레벨인 고객도 나와서 아래처럼 수정

SELECT  CID, CTEL, CNAME, CPOINT,CAMOUNT,LEVELNAME,(SELECT HIGH-CAMOUNT+1 FROM CUSTOMER WHERE CID =  C.CID AND LEVELNO !=5)  FORLEVELUP
FROM CUSTOMER C , CUS_LEVEL L
WHERE C.LEVELNO = L.LEVELNO
AND CID = 1; -- 자바에 쓸 SQL

-- 2. 폰뒤4자리(FULL) 검색 - CTEL, CNAME, CPOINT, CAMOUNT, LEVELNAME, 레벨업을 위한 쓸 돈
--    public ArrayList<CustomerDto> cTelGetCustomers(String cTel);
SELECT  CID, CTEL, CNAME, CPOINT,CAMOUNT,LEVELNAME,(SELECT HIGH-CAMOUNT+1 FROM CUSTOMER WHERE CID =  C.CID AND LEVELNO !=5)  FORLEVELUP
FROM CUSTOMER C , CUS_LEVEL L
WHERE C.LEVELNO = L.LEVELNO
AND CTEL LIKE '%'||'9999';
-- 3. 고객이름검색 - CTEL, CNAME, CPOINT, CAMOUNT, LEVELNAME, 레벨업을 위한 쓸 돈
--                       public ArrayList<CustomerDto> cNameGetCustomers(String cName);
SELECT  CID, CTEL, CNAME, CPOINT,CAMOUNT,LEVELNAME,(SELECT HIGH-CAMOUNT+1 FROM CUSTOMER WHERE CID =  C.CID AND LEVELNO !=5)  FORLEVELUP
FROM CUSTOMER C , CUS_LEVEL L
WHERE C.LEVELNO = L.LEVELNO
AND CNAME = '홍길동';
-- 4. 포인트로만 구매(1000원짜리를 포인트로만 구매) : public int buyWithPoint(int cAmount, int cId)
UPDATE CUSTOMER SET CPOINT  = CPOINT - 100 WHERE CID = 1;
-- 5. 물품구매 (1000000원짜리를 구매할 경우. 포인트는 구매금액의 5%)
    -- 물품구매시 UPDATE 2회 필요(구매누적금액 UPDATE와 LEVELNO UPDATE)
    --  public int buy(int cAmount, int cId)
 -- 5-1 포인트와 구매누적금액 변경
 UPDATE CUSTOMER SET CPOINT = CPOINT + 1000000*0.05, CAMOUNT = CAMOUNT + 1000000 WHERE CID = 1;
 SELECT * FROM CUSTOMER;
 -- 5-2 LEVELNO변경
 SELECT CNAME,CAMOUNT,C.LEVELNO 현재레벨,L.LEVELNO 바꿔야할레벨,LOW,HIGH FROM CUSTOMER C , CUS_LEVEL L
 WHERE CAMOUNT BETWEEN LOW AND HIGH;
 
  SELECT L.LEVELNO FROM CUSTOMER C , CUS_LEVEL L
 WHERE CAMOUNT BETWEEN LOW AND HIGH AND CID = 1; --ID가 1인 고객의 바꿔야 할 레벨 
 
  UPDATE CUSTOMER SET LEVELNO = (SELECT L.LEVELNO FROM CUSTOMER C , CUS_LEVEL L
 WHERE CAMOUNT BETWEEN LOW AND HIGH AND CID = 1) WHERE CID = 1;
 -- 5-1 + 5-2 합한 부분을 자바에 쓸 SQL로
UPDATE CUSTOMER SET CPOINT = CPOINT + 1000000*0.05, CAMOUNT = CAMOUNT + 1000000,
LEVELNO = (SELECT L.LEVELNO FROM CUSTOMER C , CUS_LEVEL L
 WHERE CAMOUNT+1000000 BETWEEN LOW AND HIGH AND CID = 1) WHERE CID = 1;
 SELECT * FROM CUSTOMER;
-- 6. 등급별출력 - CID, CTEL, CNAME, CPOINT, CAMOUNT, LEVELNAME, 레벨업을위한쓸돈
--              public ArrayList<CustomerDto> levelNameGetCustomers(String levelName)
SELECT  CID, CTEL, CNAME, CPOINT,CAMOUNT,LEVELNAME,(SELECT HIGH-CAMOUNT+1 FROM CUSTOMER WHERE CID =  C.CID AND LEVELNO !=5)  FORLEVELUP
FROM CUSTOMER C , CUS_LEVEL L
WHERE C.LEVELNO = L.LEVELNO
AND LEVELNAME = 'GOLD'
ORDER BY CAMOUNT DESC;
-- 7.전체출력 - CID, CTEL, CNAME, CPOINT, CAMOUNT, LEVELNAME, 레벨업을위한쓸돈
--            public ArrayList<CustomerDto> getCustomers()
SELECT  CID, CTEL, CNAME, CPOINT,CAMOUNT,LEVELNAME,(SELECT HIGH-CAMOUNT+1 FROM CUSTOMER WHERE CID =  C.CID AND LEVELNO !=5)  FORLEVELUP
FROM CUSTOMER C , CUS_LEVEL L
WHERE C.LEVELNO = L.LEVELNO
ORDER BY CAMOUNT DESC;
-- 8. 회원가입(고객전화와 고객이름은 입력받아 INSERT)
--          public int insertCustomer(String cTel, String cName)
INSERT INTO CUSTOMER (CID, CTEL,CNAME) VALUES (CUSTOMER_SEQ.NEXTVAL,'010-8888-8484','이은혜');
-- 9. 번호수정 : public int updateCustomer(String cTel, int cId)
UPDATE CUSTOMER SET CTEL = '010-4545-5454' WHERE CID = 3; 
-- 10. 회원탈퇴 : public int deleteCustomer(String cTel)
DELETE FROM CUSTOMER WHERE CID = 3;