CREATE TABLE PRODUCT(
PCODE VARCHAR2(5) PRIMARY KEY, -- 상품 상품코드
PNAME VARCHAR2(5) NOT NULL, -- 상품명
PPRICE NUMBER(6) NOT NULL, -- 상품 단가
PSTOCK NUMBER(5) NOT NULL CHECK(PSTOCK >0) --상품재고
);

DROP TABLE CUSTOMER;
CREATE TABLE CUSTOMER (
CID VARCHAR2(10) PRIMARY KEY, --고객ID
CNAME VARCHAR2(10) NOT NULL, --고객 이름
CADDRESS VARCHAR2(255) NOT NULL, --고객 주소
CTEL VARCHAR2(30) NOT NULL UNIQUE,--고객 전화번호
CEMAIL VARCHAR2(40) --고객 EMAIL
);


CREATE SEQUENCE CODE_SEQ --장바구니&주문 PK생성을 위한 선언
START WITH 1
INCREMENT BY 1
MAXVALUE 9999
MINVALUE 1
NOCYCLE 
NOCACHE;

DROP TABLE CART;
CREATE TABLE CART(
CCODE NUMBER(4) PRIMARY KEY, --장바구니 CODE
PCODE VARCHAR2(5) REFERENCES PRODUCT(PCODE), -- 상품의 상품코드
CID VARCHAR2(10) REFERENCES CUSTOMER(CID), -- 고객의 고객ID
CAMOUNT NUMBER(5) NOT NULL CHECK(CAMOUNT >0), -- 상품 수량
SELLINGPRICE NUMBER(6) NOT NULL CHECK(SELLINGPRICE >0 ), --판매금액(수량*단가)
CSELLPRICE NUMBER(7) NOT NULL
);

DROP TABLE ORDER_DELIVERY;
CREATE TABLE ORDER_DELIVERY (
ORDERCODE VARCHAR2(50) PRIMARY KEY, -- 주문번호
CID VARCHAR2(10) REFERENCES CUSTOMER(CID), -- 고객의 고객ID
ORDERDATE DATE,
OADDRESS VARCHAR2(255) NOT NULL, --받는사람 주소
OTEBL VARCHAR2(30)NOT NULL --받는사람 전화
);



DROP TABLE ORDER_PRODUCT;
CREATE TABLE ORDER_PRODUCT(
OPCODE NUMBER(4) PRIMARY KEY, --주문상품번호
ORDERCODE VARCHAR2(50) REFERENCES ORDER_DELIVERY(ORDERCODE), --주문번호 
PCODE VARCHAR2(5) REFERENCES PRODUCT(PCODE), -- 상품의 상품코드 
OPAMOUNT NUMBER(5) CHECK(OPAMOUNT > 0) NOT NULL, --주문상품수량
SELLINGPRICE NUMBER(6) CHECK(SELLINGPRICE > 0) NOT NULL --금액(수량*단가)
);


SELECT * FROM PRODUCT;
SELECT * FROM CART;
SELECT * FROM CUSTOMER;
SELECT * FROM ORDER_DELIVERY;
SELECT * FROM ORDER_PRODUCT;